disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - line_length
  - function_body_length
  - private_over_fileprivate
  - void_function_in_ternary
  - cyclomatic_complexity
  - for_where
  - type_body_length
  - multiple_closures_with_trailing_closure
  - file_length
  - force_cast
  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count

analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self

included: # paths to include during linting. `--path` is ignored if present.
  - Miramax Fillms
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

allow_zero_lintable_files: false

identifier_name:
  validates_start_with_lowercase: true
  allowed_symbols:
    - _
  min_length: 1
  max_length:
    warning: 100
    error: 1000

type_name:
  validates_start_with_lowercase: false
  min_length: 3
  max_length:
    warning: 100
    error: 1000

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
